import React from 'react';
import {createRoot} from 'react-dom/client';
import {MemoryRouter} from 'react-router-dom';
import App from './src/App';
import api from './src/api';
import {AuthProvider} from './src/context/AuthContext';
import {ToastProvider} from './src/context/ToastContext';
import './src/styles.css';
const user={id:'qa-user',displayName:'Alex Morgan',bio:'Building better habits, one day at a time.'};
const goal={targetDate:'2026-10-01',completed:false,subtasks:[{id:'walk',text:'Walk for 30 minutes',targetDays:10,completedDays:3,done:false},{id:'food',text:'Cook a balanced meal',targetDays:10,completedDays:5,done:false}]};
const posts=['health','wealth','relationships','health','wealth','relationships'].map((category,i)=>({id:`p${i}`,authorId:user.id,authorName:user.displayName,category,tag:['daily-movement','learning','family'][i%3],createdAt:Date.now(),mediaType:'image',mediaUrl:'/brand/packsomework-mark.svg',likeCount:4,commentCount:0}));
const journey={tag:'daily-movement',category:'health',goal,posts:[posts[0]],count:1};
api.defaults.adapter=async(config)=>{
 await new Promise(r=>setTimeout(r,250));
 let data={}; const url=config.url;
 if(url==='/api/auth/me')data={user};
 else if(url==='/api/posts/achievements')data={goals:[journey],achievements:[],tags:['daily-movement']};
 else if(url==='/api/posts')data={posts:config.params?.category?posts.filter(p=>p.category===config.params.category):posts};
 else if(url==='/api/stories')data={stories:[{...posts[0],id:'story1',viewedByMe:false}]};
 else if(url==='/api/posts/category-counts')data={counts:{health:2,wealth:2,relationships:2}};
 else if(url==='/api/posts/trending-tags')data={tags:[]};
 else if(url.startsWith('/api/profile'))data={user,streak:4};
 else if(url.startsWith('/api/goals/'))data={goal};
 else if(url.endsWith('/comments'))data={comments:[]};
 else if(url==='/api/follows/requests')data={requests:[]};
 else data={followers:[],following:[],users:[]};
 return {data,status:200,statusText:'OK',headers:{},config};
};
localStorage.setItem('psw_token','local-qa-fixture');
createRoot(document.getElementById('root')).render(<MemoryRouter><AuthProvider><ToastProvider><App/></ToastProvider></AuthProvider></MemoryRouter>);
