import { useCallback, useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import api from '../api';
import GoldAward from '../components/GoldAward';
import ProgressAward from '../components/ProgressAward';
import Header from '../components/Header';
import ComposerModal from '../components/ComposerModal';
import { CATEGORIES } from '../lib/format';
import { useAuth } from '../context/AuthContext';

function ReminderSettings({ initial }) {
  const [prefs,setPrefs]=useState(initial),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[error,setError]=useState('');
  const zones=typeof Intl.supportedValuesOf==='function'?Intl.supportedValuesOf('timeZone'):['UTC','Asia/Kolkata','America/New_York','Europe/London'];
  async function save(e){e.preventDefault();setBusy(true);setError('');setNotice('');try{await api.put('/api/member/preferences',prefs);setNotice(prefs.enabled?'Reminder saved. We’ll email when a task still needs a check-in.':'Task reminders are off.');}catch(err){setError(err.message);}finally{setBusy(false);}}
  return <section className="daily-panel" id="reminders"><span className="house-eyebrow">AT YOUR PACE</span><h2>Your daily nudge</h2><p>An optional email when you have an unfinished task without a photo check-in today.</p><form className="daily-reminder-form" onSubmit={save}><label className="daily-checkbox"><input type="checkbox" checked={prefs.enabled} onChange={e=>setPrefs({...prefs,enabled:e.target.checked})} /> Send me a task reminder</label><label>Time<input type="time" required value={prefs.time} onChange={e=>setPrefs({...prefs,time:e.target.value})} /></label><label>Timezone<select value={prefs.timeZone} onChange={e=>setPrefs({...prefs,timeZone:e.target.value})}>{[...new Set(['UTC',prefs.timeZone,...zones])].map(zone=><option key={zone}>{zone}</option>)}</select></label><button className="house-enter-btn" disabled={busy}>{busy?'Saving…':'Save preferences'}</button></form>{notice&&<p role="status">{notice}</p>}{error&&<p role="alert" className="auth-error">{error}</p>}<small>Emails are checked every five minutes. You can turn them off here at any time.</small></section>;
}
export default function TodayPage(){
  const {user}=useAuth();
  const [data,setData]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[task,setTask]=useState(null),[category,setCategory]=useState('all');
  const [streak,setStreak]=useState(0);
  const load=useCallback(async()=>{setError('');try{const result=await api.get('/api/member/dashboard',{params:{timeZone:Intl.DateTimeFormat().resolvedOptions().timeZone||'UTC'}});setData(result.data);}catch(err){setError(err.message);}finally{setLoading(false);}},[]);
  useEffect(()=>{load();},[load]);
  // Header's badge is always MY streak, same source of truth as everywhere
  // else — this page just never fetched it, so it always showed 0.
  useEffect(()=>{ if(!user) return; let cancelled=false; api.get(`/api/profile/${user.id}`).then(({data})=>{if(!cancelled)setStreak(data.streak);}).catch(()=>{}); return ()=>{cancelled=true;}; },[user]);
  return <><Header streak={streak} /><main className="daily-page"><header className="daily-heading"><div><p className="house-eyebrow">SMALL STEPS, RIGHT HERE</p><h1>Make today count.</h1><p>Your tasks, your momentum, your next little win.</p></div><Link className="house-enter-btn" to="/journal">Private journal ↗</Link></header>{error&&<div role="alert" className="daily-panel"><p>{error}</p><button onClick={load}>Try again</button></div>}{loading&&<p role="status">Loading your day…</p>}{data&&<><section className="daily-panel" aria-labelledby="today-tasks"><div className="daily-section-title"><h2 id="today-tasks">Today’s tasks</h2><span>{data.today} · {data.timeZone}</span></div><p>Unfinished tasks you can work on today. Deadlines belong to the goal; check-ins follow each task’s saved timezone.</p><div className="daily-filters" aria-label="Filter tasks by category">{[{id:'all',label:'All'},...CATEGORIES].map(c=><button key={c.id} aria-pressed={category===c.id} onClick={()=>setCategory(c.id)}>{c.label}</button>)}</div><div className="daily-tasks">{data.tasks.filter(t=>category==='all'||t.category===category).map(t=><article key={`${t.tag}:${t.id}`} className="daily-task"><div><span className="house-eyebrow">{t.category} · #{t.tag}</span><h3>{t.text}</h3><p>{t.checkedInToday?'✓ Checked in today': 'Ready for a check-in'} · {t.completedDays}/{t.targetDays} task days</p><small>{t.daysLeft===null?'No goal deadline':t.daysLeft<0?`${Math.abs(t.daysLeft)} days overdue`:t.daysLeft===0?'Goal due today':`${t.daysLeft} days left`} · {t.streakDays||0}-day last recorded streak</small><progress value={t.completedDays} max={t.targetDays} aria-label={`${t.text}: ${t.completedDays} of ${t.targetDays}`} /></div><button className="house-enter-btn" onClick={()=>setTask({tag:t.tag,category:t.category,index:t.index})}>＋ Photo</button></article>)}</div>{!data.tasks.some(t=>category==='all'||t.category===category)&&<p>No unfinished tasks here. <Link to="/">Start a goal from your feed →</Link></p>}</section>
      <section className="daily-panel" aria-labelledby="weekly-title"><p className="house-eyebrow">YOUR LAST SEVEN DAYS</p><h2 id="weekly-title">A week of showing up.</h2><p>{data.recap.from} — {data.recap.to}</p><div className="daily-stats"><div><strong>{data.recap.checkIns}</strong><span>Task photo check-ins</span></div><div><strong>{data.recap.goalsCompleted}</strong><span>Goals finished</span></div><div><strong>{data.recap.bestStreak}</strong><span>Best daily streak this week</span></div></div><div className="daily-chart" aria-label="Task check-ins by day">{data.recap.days.map(day=><div key={day.day}><strong>{day.count}</strong><span style={{height:`${Math.max(5,day.count/Math.max(1,...data.recap.days.map(d=>d.count))*75)}px`}} /><small>{day.day.slice(5)}</small></div>)}</div><div className="daily-category-totals">{data.recap.categories.map(c=><span key={c.category}>{CATEGORIES.find(cat=>cat.id===c.category)?.label}: <strong>{c.checkIns}</strong> check-ins</span>)}</div><small>Recaps count tracked task-photo check-ins from this feature’s release onward. Earlier progress remains on your goals.</small></section>
      <ReminderSettings initial={data.preferences} />
      <section className="daily-panel" aria-labelledby="award-progress"><div className="daily-section-title"><h2 id="award-progress">Your next awards</h2><Link to="/awards">Explore the gallery ↗</Link></div><div className="daily-awards">{data.awards.map(award=><article key={award.category}><span className="house-eyebrow">{award.category}</span><div className="task-award-collection">{award.taskAwards?.length ? award.taskAwards.map(taskAward=><ProgressAward key={taskAward.id} category={award.category} task={taskAward} />) : <p className="award-empty">Create a task to reveal your first award.</p>}</div><h3>Goal trophy</h3><p>{award.completedGoals?`${award.completedGoals} completed goals`:`${award.goalPercent}% of your closest goal${award.nearestGoal?` · #${award.nearestGoal}`:''}`}</p><progress value={award.goalPercent} max={100} aria-label={`${award.category} goal trophy progress`} /><small>Complete every task in one goal.</small><h3>Consistency badge</h3><p>{award.consistencyEarned?'Earned ✓':`${Math.min(7,award.bestStreak)} / 7 consecutive days`}</p><progress value={Math.min(7,award.bestStreak)} max={7} aria-label={`${award.category} consistency badge progress`} /><small>Check in on the same task for 7 consecutive calendar days. Best recorded streak: {award.bestStreak} days. Once earned, it stays yours.</small></article>)}</div><GoldAward earned={data.trifectaEarned} categories={data.trifectaCategories || []} /><Link to={`/profile/${user.id}/achievements`}>Visit your Achievement House →</Link></section></>}{task&&<ComposerModal kind="post" initialGoalTask={task} onClose={()=>setTask(null)} onCreated={load}/>}</main></>;
}
