import { useState } from 'react';
export default function FirstGoalGuide({ onStart }) {
  const [category, setCategory] = useState('health');
  const [tag, setTag] = useState('');
  const [task, setTask] = useState('');
  const [days, setDays] = useState(7);
  const [step, setStep] = useState(1);
  return <section className="first-goal-guide" aria-labelledby="first-goal-title"><p className="house-eyebrow">YOUR FIRST GOAL · STEP {step} OF 2</p><h2 id="first-goal-title">Start small. Make it yours.</h2><form className="auth-form" onSubmit={e => { e.preventDefault(); if (step === 1) setStep(2); else onStart({ category, tag, subtasks: [{ text: task.trim(), targetDays: Number(days) }] }); }}>{step === 1 ? <><label htmlFor="first-category">What part of life do you want to work on?</label><select id="first-category" value={category} onChange={e => setCategory(e.target.value)}><option value="health">Health</option><option value="wealth">Wealth</option><option value="relationships">Relationships</option></select><div className="auth-field"><label htmlFor="first-tag">Give your goal a short tag</label><input id="first-tag" value={tag} onChange={e => setTag(e.target.value.toLowerCase())} pattern="[a-z0-9-]{1,24}" maxLength={24} placeholder="e.g. daily-walk" required /><small>Use letters, numbers, or hyphens.</small></div></> : <><div className="auth-field"><label htmlFor="first-task">One action you can repeat</label><input id="first-task" value={task} onChange={e => setTask(e.target.value)} placeholder="e.g. Take a 20-minute walk" maxLength={140} pattern=".*\S.*" required /></div><div className="auth-field"><label htmlFor="first-days">How many task days?</label><input id="first-days" type="number" min={1} max={3650} value={days} onChange={e => setDays(e.target.value)} required /></div><p>Add an introductory photo next to save your goal. Future task-linked photos each add one day of progress.</p><button type="button" className="auth-link" onClick={() => setStep(1)}>Back</button></>}<button className="auth-submit" type="submit">{step === 1 ? 'Next: choose a task →' : 'Continue to photo →'}</button></form></section>;
}
